export function buildLockerMaterialPayload(input = {}) {
  return {
    profile_id: input.profileId || null,
    title: input.title,
    material_type: input.type,
    school: input.school,
    course: input.course || 'General',
    teacher: input.teacher || null,
    grade_level: input.grade || null,
    unit_topic: input.unit || null,
    material_year: input.year || null,
    pseudonym: input.pseudonym,
    status: input.status,
    moderation_reason: input.moderationReason || null,
    tags: input.tags || [],
    ocr_text: input.scannedText || null,
    raw_ocr_text: input.rawOcrText || input.scannedText || null,
    ocr_source: input.ocrSource || 'tesseract',
    ocr_quality: input.ocrQuality || 'good',
    ocr_confidence: input.ocrConfidence ?? null,
    ai_review: input.aiReview || {},
    vision_text: input.visionText || null,
    extraction_status: input.extractionStatus || 'ocr_good',
    preview: input.preview,
    pages: input.pages ?? 1,
    image_url: input.imageUrl || null,
    image_urls: input.imageUrls?.length ? input.imageUrls : null,
  };
}
